<div class="container">
    <div class="row">
        <h1 class="text-center" style="color: #CD6090;">Seu Pedido - Resumo</h1>
        <div class="col conteudo">
            <?php if ($this->view->carrinho != null) { ?>
                <h5 class="menu text-white p-2">Seu Pedido</h5>
                <table class="table table-hover table-sm">
                    <thead>
                        <tr>
                            <th class="text-start">Nome</th>
                            <th class="text-end">Qntd</th>
                            <th class="text-end">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->carrinho as $produto) { ?>
                            <tr id="IdTabelaProduto<?= $produto->id_produto ?>">
                                <td class="align-middle text-start">
                                    <?= $produto->nome_produto ?>
                                </td>
                                <td class="align-middle text-end">
                                    <h5>
                                        <?= $produto->quantidade ?>
                                    </h5>
                                </td>
                                <td class="align-middle text-end">
                                    <h6 id="ValorQuantidadeCarrinhoProduto<?= $produto->id_produto ?>">
                                        R$<?= number_format((float)$produto->valorQuantidade, 2, ',', '') ?>
                                    </h6>
                                </td>
                            </tr>
                        <?php } ?>
                        <tr>
                            <td>
                                <h4>
                                    Total da Compra:
                                </h4>
                            </td>
                            <td></td>
                            <td class="align-middle text-end">
                                <h4 id="ValorTotalCarrinho">
                                    R$<?= number_format((float)$this->view->total, 2, ',', '') ?>
                                </h4>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <div class="mt-3 mb-4">
                    <div>
                        <h5 class="menu text-white p-2">Seus Dados</h5>
                        <h6>
                            Nome: <?= $this->view->dadosCliente->nome ?>
                        </h6>
                        <h6>
                            E-mail: <?= $this->view->dadosCliente->email ?>
                        </h6>
                        <h6>
                            Número: <?= $this->view->dadosCliente->telefone ?>
                        </h6>
                        <h6>
                            Cidade: <?= $this->view->dadosCliente->cidade ?>
                        </h6>
                        <h6>
                            Endereço: <?= $this->view->dadosCliente->endereco ?>
                        </h6>
                        <h6>
                            CEP: <?= $this->view->dadosCliente->cep ?>
                        </h6>
                    </div>
                </div>
                <div class="mb-4">
                    <div class="col text-start">
                        <a onclick="showModalLimpar()" class="btn btn-sm btn-cadastro mx-3">Cancelar</a>
                        <a href="/carrinho" class="btn btn-sm btn-cadastro mx-2 my-1">Voltar</a>
                    </div>
                    <div class="col text-end">
                        <a href="#" class="btn btn-lg btn-cadastro mx-2">Pagar</a>
                    </div>
                </div>
            <?php } else { ?>
                <h4 class="text-center" style="color: #CD6090;">Vazio...</h4>
                <p class="text-center">Adicione produtos ao Carrinho. Você pode ir ao departamento da nossa loja para achar produtos.</p>
                <a href="/todos" class="btn btn-cadastro">Ir aos produtos</a>

            <?php } ?>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="showModalLimpar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header text-danger">
                <h3 class="modal-title">Deseja mesmo Cancelar esse Pedido?</h3>
            </div>
            <div class="modal-body row my-3">
                <div class="col text-start mx-4">
                    <a href="/limpar_carrinho" class="btn btn-danger" type="button" data-dismiss="modal">Sim</a>
                </div>
                <div class="col text-end mx-4">
                    <a onclick="closeModalCarrinho()" class="btn btn-warning" type="button" data-dismiss="modal">Não</a>
                </div>
            </div>

        </div>
    </div>
</div>