<div class="container">
    <div class="row">
        <h1 class="text-center" style="color: #CD6090;">Seu Pedido - Resumo</h1>
        <div class="col conteudo">
            <?php if ($this->view->carrinho != null) { ?>
                <h5 class="menu text-white p-2">Seu Pedido</h5>
                <h6>Código do Pedido: <?= $_SESSION['codigo_pedido'] ?></h6>

                <table class="table table-hover table-sm">
                    <thead class="text-white background-loja">
                        <tr>
                            <th class="text-start">Produto</th>
                            <th class="text-end">Qntd</th>
                            <th class="text-end">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->carrinho as $produto) { ?>
                            <tr id="IdTabelaProduto<?= $produto->id_produto ?>">
                                <td class="align-middle text-start">
                                    <?= $produto->nome_produto ?>
                                </td>
                                <td class="align-middle text-end">
                                    <h5>
                                        <?= $produto->quantidade ?>
                                    </h5>
                                </td>
                                <td class="align-middle text-end">
                                    <h6 id="ValorQuantidadeCarrinhoProduto<?= $produto->id_produto ?>">
                                        R$<?= number_format((float)$produto->valorQuantidade, 2, ',', '') ?>
                                    </h6>
                                </td>
                            </tr>
                        <?php } ?>
                        <tr>
                            <td>
                                <h4>
                                    Total da Compra:
                                </h4>
                            </td>
                            <td></td>
                            <td class="align-middle text-end">
                                <h4 id="ValorTotalCarrinho">
                                    R$<?= number_format((float)$this->view->total, 2, ',', '') ?>
                                </h4>
                            </td>
                        </tr>
                    </tbody>
                </table>

                <div class="mt-3 mb-4">
                    <div>
                        <h5 class="menu text-white p-2">Seus Dados</h5>
                        <h6>
                            Nome: <?= $this->view->dadosCliente->nome ?>
                        </h6>
                        <h6>
                            E-mail: <?= $this->view->dadosCliente->email ?>
                        </h6>
                        <h6>
                            Telefone para contato: <?= $this->view->dadosCliente->telefone ?>
                        </h6>
                        <h6>
                            CEP: <?= $this->view->dadosCliente->cep ?>
                        </h6>
                        <h6>
                            Rua: <?= $this->view->dadosCliente->rua ?>
                        </h6>
                        <h6>
                            Número da Residência: <?= $this->view->dadosCliente->numero_residencia ?>
                        </h6>
                        <h6>
                            Bairro: <?= $this->view->dadosCliente->bairro ?>
                        </h6>
                        <h6>
                            Cidade: <?= $this->view->dadosCliente->cidade ?>
                        </h6>
                    </div>
                </div>

                <div class="mb-2">
                    <div class="form-check mx-3 my-4">
                        <input class="form-check-input" onchange="enderecoAlternativo()" type="checkbox" value="" id="enderecoAlternativo">
                        <label class="form-check-label" for="enderecoAlternativo">
                            Definir outro endereço
                        </label>
                    </div>
                    <div id="campoEnderecoAlternativo" style="display: none;">
                        <form class="row needs-validation mb-3" method="" action="">
                            <div class="row">
                                <div class="col-md">

                                    <div class="form-floating mb-2">
                                        <input class="form-control" id="CEP" placeholder="CEP">
                                        <label for="CEP">CEP</label>
                                    </div>

                                    <div class="form-floating mb-2">
                                        <input class="form-control" id="NumeroCasa" placeholder="Número">
                                        <label for="NumeroCasa">Número da Residência</label>
                                    </div>

                                    <div class="form-floating mb-2">
                                        <input class="form-control" id="Rua" placeholder="Endereço" readonly>
                                        <label for="Rua">Sua Rua</label>
                                    </div>

                                    <div class="form-floating mb-2">
                                        <input class="form-control" id="Bairro" placeholder="Bairro" readonly>
                                        <label for="Bairro">Bairro</label>
                                    </div>

                                    <div class="form-floating mb-2">
                                        <input class="form-control" id="Cidade" placeholder="Cidade" readonly>
                                        <label for="Cidade">Cidade</label>
                                    </div>

                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="mt-3 mb-4">
                    <div>
                        <h5 class="menu text-white p-2">Método de Envio</h5>

                        <div class="form-check mx-3 mt-4">
                            <input class="form-check-input" type="checkbox" value="" id="metodoEnvioCorreios">
                            <label class="form-check-label" for="metodoEnvioCorreios">
                                Correios
                            </label>
                        </div>
                        <div id="EnvioCorreios" style="display: none;">
                            <h6 class="mx-3 mt-2">Valor: R$20,00</h6>
                            <p class="mx-3">O preço para envio pelos Correios vai ser Adicionado ao Valor final</p>
                        </div>


                        <div class="form-check mx-3 mb-4">
                            <input class="form-check-input" type="checkbox" value="" id="metodoEnvioExcursao">
                            <label class="form-check-label" for="metodoEnvioExcursao">
                                Excursão
                            </label>
                        </div>
                        <div id="campoNomeExcursao" style="display: none;">
                            <form class="row needs-validation mb-3">
                                <div class="row">
                                    <div class="col-md">
                                        <div class="form-floating mb-2">
                                            <input class="form-control" id="nomeExcursao" placeholder="nomeExcursao">
                                            <label for="nomeExcursao">Nome da Excursão pela qual deseja receber</label>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>

                    </div>
                </div>

                <div class="row mb-4">
                    <div class="col text-start">
                        <a id="buttonModalLimpar" class="btn btn-cadastro mx-3">Limpar Carrinho</a>
                    </div>
                    <div class="col text-end">
                        <a href="<?= BASE_URL ?>todos" class="btn btn-cadastro mx-4 my-1">Mais produtos</a>
                    </div>
                </div>

                <div class="col my-3 text-end">
                    <!-- href="<?= BASE_URL ?>confirmar_pedido" -->
                    <button id="confirmarPedido" type="submit" class="btn btn-lg btn-cadastro mx-2">Finalizar Pedido</button>
                </div>

            <?php } else { ?>
                <h4 class="text-center" style="color: #CD6090;">Vazio...</h4>
                <p class="text-center">Adicione produtos ao Carrinho. Você pode ir ao departamento da nossa loja para achar produtos.</p>
                <a href="<?= BASE_URL ?>todos" class="btn btn-cadastro">Ir aos produtos</a>

            <?php } ?>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="showModalLimpar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header text-danger">
                <h3 class="modal-title">Deseja mesmo Cancelar esse Pedido?</h3>
            </div>
            <div class="modal-body row my-3">
                <div class="col text-start mx-4">
                    <a href="<?= BASE_URL ?>limpar_carrinho" class="btn btn-danger" type="button" data-dismiss="modal">Sim</a>
                </div>
                <div class="col text-end mx-4">
                    <a id="closeModalLimpar" class="btn btn-warning" type="button" data-dismiss="modal">Não</a>
                </div>
            </div>

        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="selecionaMetodoEnvio" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header text-danger">
                <h3 class="modal-title">Selecione um método de envio para Finalizar</h3>
            </div>
            <div class="modal-body row my-3">
                <div class="col text-center mx-4">
                    <a id="closeSelecionaMetodoEnvio" class="btn btn-warning" type="button" data-dismiss="modal">Fechar</a>
                </div>
            </div>

        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="preencherCampoExcursao" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header text-danger">
                <h3 class="modal-title">Infome o nome da excursão pela qual você quer receber.</h3>
            </div>
            <div class="modal-body row my-3">
                <div class="col text-center mx-4">
                    <a id="closePreencherCampoExcursao" class="btn btn-warning" type="button" data-dismiss="modal">Fechar</a>
                </div>
            </div>

        </div>
    </div>
</div>