<div class="container">
    <div class="row mt-3">
        <div class="col conteudo">
            <h3 class="text-center mb-3 text-loja">Histórico de Pedidos</h3>

            <?php if (count($this->view->historicoPedido) > 0) { ?>

                <table class="table table-hover table-sm">
                    <thead class="text-white background-loja">
                        <tr>
                            <th scope="col" class="align-middle text-start">Data do Pedido</th>
                            <th scope="col" class="align-middle text-start">Código do Pedido</th>
                            <th scope="col" class="align-middle text-start">Status do Pedido</th>
                            <th scope="col" class="align-middle text-start">Mensagem</th>
                            <th scope="col"></th>

                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->historicoPedido as $pedido) { ?>
                            <tr>
                                <td class="align-middle text-start">
                                    <p><?= $pedido->data_pedido ?></p>
                                </td>
                                <td class="align-middle text-start">
                                    <p><?= $pedido->codigo_pedido ?></p>
                                </td>
                                <td class="align-middle text-start">
                                    <p><?= $pedido->status_pedido ?></p>
                                </td>
                                <td class="align-middle text-start">
                                    <p><?= $pedido->mensagem ?></p>
                                </td>
                                <td class="align-middle text-start">
                                    <a class="btn btn-sm btn-cadastro" href="<?= BASE_URL ?>detalhes_pedido?id_pedido=<?= $pedido->id_pedido ?>">Detalhes</a>
                                </td>
                            </tr>
                        <?php } ?>

                    </tbody>
                </table>

                <div class="row">
                    <div class="col ">
                        <ul class="pagination justify-content-center text-loja text-paginacao">
                            <li class="page-item"><a class="page-link" href="<?= BASE_URL ?>historico_pedidos?pagina=1">Primeira</a></li>
                            <?php for ($i = 1; $i <= $this->view->totalPaginas; $i++) { ?>
                                <li class="page-item  <?= $this->view->paginaAtiva == $i ? 'active' : '' ?>">

                                    <a class="page-link" href="<?= BASE_URL ?>historico_pedidos?pagina=<?= $i ?>"><?= $i ?></a>

                                </li>
                            <?php } ?>
                            <li class="page-item"><a class="page-link" href="<?= BASE_URL ?>historico_pedidos?pagina=<?= $this->view->totalPaginas ?>">Última</a></li>
                        </ul>
                    </div>
                </div>

                <div class="row mb-4">
                    <div class="col text-center">
                        <a type="submit" href="<?= BASE_URL ?>minha_conta" class="btn btn-lg btn-cadastro mx-4">Voltar</a>
                    </div>
                </div>


            <?php } else { ?>
                <p class="text-center text-loja">
                    Você ainda não realizou nenhum pedido, quando fizer um pedido poderá vê-lo aqui.
                </p>
            <?php } ?>
        </div>
    </div>
</div>