<div class="container">
    <div class="row mt-3">
        <div class="col conteudo">
            <h3 class="text-center mb-3 text-loja">Histórico de Pedidos</h3>

            <?php if (count($this->view->historicoPedido) > 0) { ?>

                <table class="table table-hover table-sm">
                    <thead class="text-white background-loja">
                        <tr>
                            <th scope="col" class="align-middle text-start">Data do Pedido</th>
                            <th scope="col" class="align-middle text-start">Código do Pedido</th>
                            <th scope="col" class="align-middle text-start">Status do Pedido</th>
                            <th scope="col" class="align-middle text-start">Mensagem</th>
                            <th scope="col"></th>

                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->historicoPedido as $pedido) { ?>
                            <tr>
                                <td class="align-middle text-start">
                                    <p><?= $pedido->data_pedido ?></p>
                                </td>
                                <td class="align-middle text-start">
                                    <p><?= $pedido->codigo_pedido ?></p>
                                </td>
                                <td class="align-middle text-start">
                                    <p><?= $pedido->status_pedido ?></p>
                                </td>
                                <td class="align-middle text-start">
                                    <p><?= $pedido->mensagem ?></p>
                                </td>
                                <td class="align-middle text-start">
                                    <a class="btn btn-cadastro" href="<?= BASE_URL ?>detalhes_pedido?id_pedido=<?= $pedido->id_pedido ?>">Detalhes</a>
                                </td>
                            </tr>
                        <?php } ?>

                    </tbody>
                </table>
                <div class="row mb-4">
                    <div class="col text-start">
                        <h4 class="text-loja">Total de Pedidos: <?= count($this->view->historicoPedido) ?></h4>
                    </div>
                    <div class="col text-end">
                        <a type="submit" href="<?= BASE_URL ?>minha_conta" class="btn btn-cadastro mx-4">Voltar</a>
                    </div>
                </div>


            <?php } else { ?>
                <p class="text-center" style="color:#CD6090;">
                    Você ainda não realizou nenhum pedido, quando fizer um pedido poderá vê-lo aqui.
                </p>
            <?php } ?>
        </div>
    </div>
</div>