<div class="container">
    <div class="row">
        <?php if ($this->view->listaPedidos['pedidosPreparo'] > 0) { ?>
            <div class="alert alert-info">
                <p>Existe um total de <strong><?= $this->view->listaPedidos['pedidosPreparo'] ?> pedido(s)</strong> á ser <strong>preparado(s)</strong>.</p>
            </div>
        <?php } ?>
        <div class="col d-flex flex-column background-loja text-white">
            <a class="justify-content-start d-flex btn btn-cadastro" href="">
                <h4 class="m-0 p-3"><i class="fas fa-boxes"></i> Pedidos Registrados: <?= $this->view->listaPedidos['pedidosTotal'] ?></h4>
            </a>
            <a class="justify-content-start d-flex btn btn-cadastro" href="">
                <h4 class="m-0 p-3">
                    <i class="fas fa-box-open"></i> Pedidos Pendentes: <?= $this->view->listaPedidos['pedidosPendentes'] ?>
                </h4>
            </a>
            <a class="justify-content-start d-flex btn btn-cadastro" href="">
                <h4 class="m-0 p-3">
                    <i class="fas fa-truck-loading"></i> Pedidos em Preparo: <?= $this->view->listaPedidos['pedidosPreparo'] ?>
                </h4>
            </a>
            <a class="justify-content-start d-flex btn btn-cadastro" href="">
                <h4 class="m-0 p-3">
                    <i class="fas fa-people-carry"></i> Pedidos Enviados: <?= $this->view->listaPedidos['pedidosEnviados'] ?>
                </h4>
            </a>
            <a class="justify-content-start d-flex btn btn-cadastro" href="">
                <h4 class="m-0 p-3">
                    <i class="fas fa-check-square"></i> Pedidos Finalizados: <?= $this->view->listaPedidos['pedidosFinalizados'] ?>
                </h4>
            </a>
        </div>
    </div>
</div>