<div class="container">
    <div class="row">
        <div class="col d-flex flex-column background-loja text-white">
            <a class="justify-content-start d-flex btn btn-cadastro" href="">
                <h4 class="m-0 p-3"><i class="fas fa-boxes"></i> Pedidos Registrados: ##</h4>
            </a>
            <a class="justify-content-start d-flex btn btn-cadastro" href="">
                <h4 class="m-0 p-3">
                    <i class="fas fa-box-open"></i> Pedidos Pendentes: ##
                </h4>
            </a>
            <a class="justify-content-start d-flex btn btn-cadastro" href="">
                <h4 class="m-0 p-3">
                    <i class="fas fa-truck-loading"></i> Pedidos em Preparo: ##
                </h4>
            </a>
            <a class="justify-content-start d-flex btn btn-cadastro" href="">
                <h4 class="m-0 p-3">
                    <i class="fas fa-people-carry"></i> Pedidos Enviados: ##
                </h4>
            </a>
            <a class="justify-content-start d-flex btn btn-cadastro" href="">
                <h4 class="m-0 p-3">
                    <i class="fas fa-check-square"></i> Pedidos Finalizados: ##
                </h4>
            </a>
        </div>
    </div>
</div>