<div class="container tela-admin">
    <div class="row">
        <div class="col">
            <form class="form-admin" action="<?= BASE_URL . 'confirma_login_admin' ?>" method="post">
                <h1 class="text-center">Login Admin</h1>

                <div class="form-floating mb-2">
                    <input name="admin" type="text" class="form-control" id="Admin" placeholder="Admin" required>
                    <label for="Admin">Admin</label>
                </div>

                <div class="form-floating mb-2">
                    <input name="senha" type="password" class="form-control" id="password" placeholder="Senha" required>
                    <label for="password">Senha</label>
                </div>
            </form>
        </div>
    </div>
</div>
</div>