<div class="container">
    <div class="row">
        <h1 class="text-center" style="color: #CD6090;">Carrinho</h1>
        <div class="col conteudo">
            <?php if ($this->view->carrinho != null) { ?>
                <table class="table table-hover table-sm">
                    <thead>
                        <tr>
                            <th scope="col"></th>
                            <th scope="col" class="text-center">Nome</th>
                            <th scope="col" class="text-center">Preço(Und)</th>
                            <th scope="col" class="text-center">Qntd</th>
                            <th scope="col" class="text-center">Total</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->carrinho as $produto) { ?>
                            <tr id="IdTabelaProduto<?= $produto->id_produto ?>">
                                <td class="d-flex flex-column">
                                    <img src="assets/img/<?= $produto->imagem ?>" class="img-fluid d-block img-produto d-flex align-center" width="120px">
                                </td>
                                <td class="align-middle text-center">
                                    <?= $produto->nome_produto ?>
                                </td>
                                <td id="ValorProduto<?= $produto->id_produto ?>" class="align-middle text-center">

                                    R$<?= preg_replace("/\./", ",", $produto->preco) ?>

                                </td>
                                <td class="align-middle text-center">
                                    <h5>
                                        <i onclick="menosUmProduto(<?= $produto->id_produto ?>)" class="fas fa-minus text-danger"></i>
                                        <span id="QuantidaCarrinhoProduto<?= $produto->id_produto ?>" class="text-center">
                                            <?= $produto->quantidade ?>
                                        </span>
                                        <i onclick="maisUmProduto(<?= $produto->id_produto ?>)" class="fas fa-plus text-success"></i>
                                    </h5>
                                </td>
                                <td class="align-middle text-center">
                                    <h6 id="ValorQuantidadeCarrinhoProduto<?= $produto->id_produto ?>">
                                        R$<?= number_format((float)$produto->valorQuantidade, 2, ',', '') ?>
                                    </h6>
                                </td>
                                <td class="align-middle text-start">
                                    <span onclick="removerProdutoCarrinho(<?= $produto->id_produto ?>)" class="text-danger" value=""><i class="fas fa-times"></i></span>
                                </td>
                            </tr>
                        <?php } ?>
                        <tr>
                            <td>
                                <h3>
                                    Total da Compra:
                                </h3>
                            </td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td class="align-middle">
                                <h3 id="ValorTotalCarrinho">
                                    R$<?= number_format((float)$this->view->total, 2, ',', '') ?>
                                </h3>
                            </td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
                <div class="row mb-4">
                    <div class="col text-start">
                        <a id="buttonModalLimpar" class="btn btn-cadastro mx-3">Limpar Carrinho</a>
                        <a href="/todos" class="btn btn-cadastro mx-4 my-1">Mais produtos</a>
                    </div>
                    <div class="col text-end">
                        <a href="/finalizar_pedido" class="btn btn-cadastro mx-2">Finarlizar</a>
                    </div>
                </div>
            <?php } else { ?>
                <h4 class="text-center" style="color: #CD6090;">Vazio...</h4>
                <p class="text-center">Adicione produtos ao Carrinho. Você pode ir ao departamento da nossa loja para achar produtos.</p>
                <a href="/todos" class="btn btn-cadastro">Ir aos produtos</a>
            <?php } ?>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="showModalLimpar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header text-danger">
                <h3 class="modal-title">Deseja mesmo limpar o Carrinho?</h3>
            </div>
            <div class="modal-body row my-3">
                <div class="col text-start mx-4">
                    <a href="/limpar_carrinho" class="btn btn-danger" type="button" data-dismiss="modal">Sim</a>
                </div>
                <div class="col text-end mx-4">
                    <a id="closeModalLimpar" class="btn btn-warning" type="button" data-dismiss="modal">Não</a>
                </div>
            </div>

        </div>
    </div>
</div>