<div class="container mt-1">
    <div class="row">
        <div class="col-12 mt-2" style="color: #CD6090;">
            <h1 class="text-center">Os Mais Vendidos</h1>
            <div class="container-produtos card-body row">
                <div class="card-produto text-center">
                    <img src="assets/img/produto/macaquinho/macaquinho_preto.jpeg" alt="" class="img-fluid img-produto card-img-top">
                    <h4 class="card-title mt-1 ">
                        Macaquinho 2 </h4>
                    <h5 class="card-text ">Preço: R$30,00</h5>
                    <div class="align-bottom button-card">
                        <button onclick="adicionarCarrinho(2)" class="btn btn-cadastro btn-lg">Adicionar <i class="fas fa-cart-plus"></i></button>
                    </div>
                </div>
                <div class="card-produto text-center">
                    <img src="assets/img/produto/macaquinho/macaquinho_preto2.jpeg" alt="" class="img-fluid img-produto card-img-top">
                    <h4 class="card-title mt-1 ">
                        Macaquinho 3 </h4>
                    <h5 class="card-text ">Preço: R$30,00</h5>
                    <div class="align-bottom button-card">
                        <button onclick="adicionarCarrinho(3)" class="btn btn-cadastro btn-lg">Adicionar <i class="fas fa-cart-plus"></i></button>
                    </div>
                </div>
                <div class="card-produto text-center">
                    <img src="assets/img/produto/macaquinho/macaquinho_vermelho.jpeg" alt="" class="img-fluid img-produto card-img-top">
                    <h4 class="card-title mt-1 ">
                        Macaquinho 4 </h4>
                    <h5 class="card-text ">Preço: R$30,00</h5>
                    <div class="align-bottom button-card">
                        <button onclick="adicionarCarrinho(4)" class="btn btn-cadastro btn-lg">Adicionar <i class="fas fa-cart-plus"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 mb-4 mt-2 d-flex flex-column ">
            <h1 class=" text-center" style="color: #CD6090;">Nossa Localização</h1>
            <figure class="figure d-flex justify-content-center">
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3981.384157910444!2d-38.5266474!3d-3.726135!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x7c7496c8833f055%3A0x6f5a58686d1f8091!2zRXhwYW5zw6NvIEZlaXLDo28gU8OjbyBKb3PDqQ!5e0!3m2!1spt-BR!2sbr!4v1615408743337!5m2!1spt-BR!2sbr" width="600" height="350" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
            </figure>
            <p class="text-center" style="color: #CD6090;">
                Governador Sampaio 95 <br>
                Feirão São José Expansão<br>
                Loja 86
            </p>
        </div>
    </div>
</div>