<div class="container-fluid">
    <div class="row mt-3">
        <div class="col-sm-6 offset-sm-3">
            <h3 class="text-center mb-3" style="color:#CD6090;">Fazer Login</h3>
            <form class="row needs-validation mb-3" method="post" action="/valida_login">
                <div class="row">
                    <div class="col-md">
                        <?php if (isset($_GET['erro']) && $_GET['erro'] == 'campoVazio') { ?>
                            <div>
                                <p class="alert alert-danger text-center p-2">Preencha todos os campos para fazer o Login</p>
                            </div>
                        <?php } ?>

                        <?php if (isset($_GET['erro']) && $_GET['erro'] == 'senha') { ?>
                            <div>
                                <p class="alert alert-danger text-center p-2">Senha ou E-mail incorreto, tente novamente</p>
                            </div>
                        <?php } ?>

                        <?php if (isset($_GET['erro']) && $_GET['erro'] == 'email') { ?>
                            <div>
                                <p class="alert alert-danger text-center p-2">E-mail não cadastrado.
                                    Por favor tente usar outro email ou faça um <a href="?page=newUser">Cadastro </a>desse E-mail
                                </p>
                            </div>
                        <?php } ?>
                        <?php if (isset($_GET['finalizarPedido']) && $_GET['finalizarPedido'] == true) { ?>
                            <div>
                                <p class="alert alert-warning text-center p-2">Faça Login para finalizar o pedido</p>
                            </div>
                        <?php } ?>

                        <div class="form-floating mb-2">
                            <input name="email" type="email" class="form-control" id="floatingInputGrid" placeholder="E-mail" value="">
                            <label for="floatingInputGrid">E-mail</label>
                        </div>

                        <div class="form-floating mb-2">
                            <input name="senha" type="password" class="form-control" id="floatingInputGrid" placeholder="Senha" value="">
                            <label for="floatingInputGrid">Senha</label>
                        </div>

                    </div>
                    <div class="d-grid gap-2 mt-2">
                        <input type="submit" value="Login" class="btn btn-cadastro">
                    </div>
                </div>
                <p class="mt-2 text-center">
                    Ainda não é cadastrado? Crie uma conta na loja agora mesmo
                    <a class="btn btn-cadastro" href="/criar_conta">Criar Conta</a>
                </p>
            </form>
        </div>
    </div>
</div>