<div class="container col-12">
    <div class="row">
        <h1 class="mt-3" style="color: #CD6090;">Departamentos: <?= $this->view->categoria ?></h1>
    </div>
    <div class="container-produtos card-body row">
        <?php foreach ($this->view->produto as $produto) { ?>
            <div class="card-produto text-center">
                <img src="assets/img/<?= $produto->imagem ?>" alt="" class="img-fluid img-produto card-img-top">
                <h4 class="card-title mt-1 ">
                    <?= $produto->nome_produto ?>
                </h4>
                <h5 class="card-text ">Preço: R$<?= preg_replace("/\./", ",", $produto->preco) ?></h5>
                <div class="align-bottom button-card">
                    <?php if ($produto->estoque > 0) { ?>
                        <button onclick="adicionarCarrinho(<?= $produto->id_produto ?>)" class="btn btn-cadastro btn-lg">Adicionar <i class="fas fa-cart-plus"></i></button>
                    <?php } else { ?>
                        <button class="btn disabled btn-danger ">Produto indisponível <i class="fas fa-exclamation-triangle"></i></button>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
    </div>
</div>