<div class="container col-12 my-3">
    <div class="row">
        <h1 class="mt-2 text-center text-loja"><?= $this->view->categoria ?></h1>
    </div>
    <div class="container-produtos card-body row">
        <?php foreach ($this->view->produto as $produto) { ?>
            <div class="card-produto text-center">
                <img src="assets/img/<?= $produto->imagem ?>" alt="" class="img-fluid img-produto card-img-top">
                <h4 class="card-title mt-1 ">
                    <?= $produto->nome_produto ?>
                </h4>
                <h5 class="card-text ">Preço: R$<?= preg_replace("/\./", ",", $produto->preco) ?></h5>
                <div class="align-bottom button-card">
                    <?php if ($produto->estoque > 0) { ?>
                        <button onclick="adicionarCarrinho(<?= $produto->id_produto ?>)" class="btn btn-cadastro btn-lg">Adicionar <i class="fas fa-cart-plus"></i></button>
                    <?php } else { ?>
                        <button class="btn disabled btn-danger ">Produto indisponível <i class="fas fa-exclamation-triangle"></i></button>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>

    </div>
    <div class="row">
        <div class="col ">
            <ul class="pagination justify-content-center text-loja text-paginacao">
                <li class="page-item"><a class="page-link" href="<?= BASE_URL ?>todos?pagina=1<?= $this->view->categoria == 'Todos os Produtos' ? '' : '&categoria=' . $this->view->categoria ?>">Primeira</a></li>
                <?php for ($i = 1; $i <= $this->view->totalPaginas; $i++) { ?>
                    <li class="page-item  <?= $this->view->paginaAtiva == $i ? 'active' : '' ?>">
                        <?php if ($this->view->categoria == 'Todos os Produtos') { ?>
                            <a class="page-link" href="<?= BASE_URL ?>todos?pagina=<?= $i ?>"><?= $i ?></a>
                        <?php } else { ?>
                            <a class="page-link" href="<?= BASE_URL ?>produtos?pagina=<?= $i ?>&categoria=<?= $this->view->categoria ?>"><?= $i ?></a>
                        <?php } ?>
                    </li>
                <?php } ?>
                <li class="page-item"><a class="page-link" href="<?= BASE_URL ?>todos?pagina=<?= $this->view->totalPaginas ?><?= $this->view->categoria == 'Todos os Produtos' ? '' : '&categoria=' . $this->view->categoria ?>">Última</a></li>
            </ul>
        </div>
    </div>
</div>