<div class="container mt-3">
    <div class="row">
        <h1 class="mt-3" style="color: #CD6090;"><?= $this->view->categoria ?></h1>
    </div>
    <div class="alert alert-warning" role="alert">
        <h4 class="alert-heading">Ops...</h4>
        <p>
            Infelizmente não temos nenhum produto dessa categoria disponível no momento.
            Mas não se preocupe você pode explorar outros departamentos em nossa loja.
        </p>
        <a class="btn btn-warning" href="/">Ir para o Inicio</a>

    </div>
</div>