<div class="container-fluid">
    <div class="row mt-3">
        <div class="col-sm-6 offset-sm-3 ml-2">
            <h3 class="text-center mb-3" style="color:#CD6090;">Alterar Senha</h3>
            <form class="row needs-validation mb-3" method="post" action="<?= BASE_URL ?>salvar_alteracao_senha">
                <div class="row">
                    <div class="col-md">

                        <?php if (isset($_GET['erro']) && $_GET['erro'] == 'campoVazio') { ?>
                            <div>
                                <p class="alert alert-danger text-center p-2">Preencha todos os campos para fazer o cadastro</p>
                            </div>
                        <?php } ?>

                        <?php if (isset($_GET['erro']) && $_GET['erro'] == 'senha') { ?>
                            <div>
                                <p class="alert alert-danger text-center p-2">Senhas novas diferentes, tente novamente</p>
                            </div>
                        <?php } ?>

                        <?php if (isset($_GET['erro']) && $_GET['erro'] == 'senha2') { ?>
                            <div>
                                <p class="alert alert-danger text-center p-2">Senha atual incorreta, tente novamente</p>
                            </div>
                        <?php } ?>

                        <div class="form-floating mb-2">
                            <input name="senhaAtual" type="password" class="form-control" id="Senha" placeholder="Senha" value="" required>
                            <label for="Senha">Senha Atual</label>
                        </div>

                        <div class="form-floating mb-2">
                            <input name="novaSenha" type="password" class="form-control" id="novaSenha" placeholder="novaSenha" value="" required>
                            <label for="novaSenha">Nova Senha</label>
                        </div>

                        <div class="form-floating mb-2">
                            <input name="senhaNovaConfirmada" type="password" class="form-control" id="ConfirmeSenha" placeholder="Confirme a Senha" value="" required>
                            <label for="ConfirmeSenha">Confirme Nova Senha</label>
                        </div>

                    </div>
                    <div class="row mt-4 text-center">
                        <div class="col justify-content-between">
                            <input type="submit" value="Salvar Alteração" class="btn btn-cadastro  mx-4">
                            <a type="submit" href="<?= BASE_URL ?>minha_conta" class="btn btn-cadastro  mx-4">Voltar</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>