<div class="container-fluid mt-3">
    <div class="alert alert-warning" role="alert">
        <h4 class="alert-heading">E-mail enviado para confirmação!</h4>
        <p>
            Foi enviado um E-mail para você com o link para validar a sua conta.
            Verifique sua caixa de entrada ou a pasta de SPAM.
        </p>
        <a class="btn btn-warning" href="?page=inicio">Voltar</a>

    </div>
</div>