<div class="container">
    <div class="row mt-3">
        <div class="col conteudo">
            <h3 class="text-center mb-3" style="color:#CD6090;">Histórico de Pedidos</h3>

            <?php if ($this->view->historicoPedido != null) { ?>
                <pre>
                    <?php
                    print_r($this->view->historicoPedido);
                    ?>
                </pre>
            <?php } else { ?>
                <p class="text-center" style="color:#CD6090;">
                    Você ainda não realizou nenhum pedido, quando fizer um pedido poderá vê-lo aqui.
                </p>
            <?php } ?>
        </div>
    </div>
</div>