<div class="container">
    <div class="row" style="color: #CD6090;">
        <div class="col conteudo">
            <h2 class="menu text-white p-2">Seus Dados:</h2>
            <div class="col">
                <div class="row mb-2">
                    <div class="col text-start">
                        <h5>Nome: <span><?= $this->view->dadosUser->nome ?> </span></h5>
                    </div>
                    <div class="col text-end">
                        <i class="fas fa-edit fa-lg" style="color: #CD6090;"></i>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col text-start">
                        <h5>E-mail: <span><?= $this->view->dadosUser->email ?></span></h5>
                    </div>
                    <div class="col text-end">
                        <i class="fas fa-edit fa-lg" style="color: #CD6090;"></i>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col text-start">
                        <h5>CEP: <span><?= $this->view->dadosUser->cep ?></span></h5>
                    </div>
                    <div class="col text-end">
                        <i class="fas fa-edit fa-lg" style="color: #CD6090;"></i>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col text-start">
                        <h5>Número da Redidência: <span><?= $this->view->dadosUser->numero_residencia ?></span></h5>
                    </div>
                    <div class="col text-end">
                        <i class="fas fa-edit fa-lg" style="color: #CD6090;"></i>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col text-start">
                        <h5>Telefone: <span><?= $this->view->dadosUser->contato ?></span></h5>
                    </div>
                    <div class="col text-end">
                        <i class="fas fa-edit fa-lg" style="color: #CD6090;"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>