<div class="container mt-3">
    <div class="row text-loja">
        <div class="col conteudo">
            <?php if (isset($_GET['alteracao']) && $_GET['alteracao'] == 'dadosPessoais') { ?>
                <div>
                    <p class="alert alert-success text-center p-2">Dados Pessoais Alterados com Sucesso</p>
                </div>
            <?php } ?>

            <?php if (isset($_GET['alteracao']) && $_GET['alteracao'] == 'senha') { ?>
                <div>
                    <p class="alert alert-success text-center p-2">Senha Alterada com Sucesso</p>
                </div>
            <?php } ?>

            <h2 class="background-loja text-white p-2">Seus Dados:</h2>

            <div class="col">
                <div class="row mb-2">
                    <div class="col text-start">
                        <h5>Nome: <span><?= $this->view->dadosUser->nome ?> </span></h5>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col text-start">
                        <h5>E-mail: <span><?= $this->view->dadosUser->email ?></span></h5>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col text-start">
                        <h5>CEP: <span><?= $this->view->dadosUser->cep ?></span></h5>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col text-start">
                        <h5>Número da Redidência: <span><?= $this->view->dadosUser->numero_residencia ?></span></h5>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col text-start">
                        <h5>Telefone: <span><?= $this->view->dadosUser->contato ?></span></h5>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-4 text-center">
            <div class="col justify-content-between">
                <a href="<?= BASE_URL ?>historico_pedidos" class="btn btn-cadastro mx-4 my-1"><i class="fas fa-list-alt"></i> Histórico de Pedidos</a>
                <a href="<?= BASE_URL ?>alterar_dados_pessoais" class="btn btn-cadastro mx-4 my-1"><i class="fas fa-user-edit"></i> Alterar Dados Pessoais</a>
                <a href="<?= BASE_URL ?>alterar_senha" class="btn btn-cadastro mx-4 my-1"><i class="fas fa-key"></i> Alterar Senha</a>
            </div>
        </div>
    </div>
</div>