<!DOCTYPE html>
<html lang="pt-br" class="h-100">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sticky-footer-navbar/">
    <link rel="stylesheet" href="assets_admin/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets_admin/css/all.min.css">
    <link rel="stylesheet" href="assets_admin/css/app.css">
    <title><?= APP_NAME ?></title>
</head>

<body class="d-flex flex-column h-100">

    <header>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md fixed-top navbar-dark menu">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand logo" href="/"><?= 'Gracy' ?></a>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class=" nav-item">
                            <a class="nav-link" href="<?= BASE_URL ?>admin/home"><i class="fas fa-home"></i> Home</a>
                        </li>
                        <li class=" nav-item">
                            <a class="nav-link" href="<?= BASE_URL ?>admin/pedidos"><i class="fas fa-book-open"></i> Pedidos</a>
                        </li>
                        <li class=" nav-item">
                            <a class="nav-link" href="<?= BASE_URL ?>admin/produtos"><i class="fas fa-tshirt"></i></i> Produtos</a>
                        </li>
                        <li class=" nav-item">
                            <a class="nav-link" href="<?= BASE_URL ?>admin/clientes"><i class="fas fa-users"></i></i> Clientes</a>
                        </li>
                        <li class=" nav-item">
                            <a class="nav-link" href="<?= BASE_URL ?>admin/sair"><i class="fas fa-sign-out-alt"></i> Sair</a>
                        </li>

                    </ul>

                </div>

            </div>
        </nav>

    </header>

    <!-- Begin page content -->
    <main class="flex-shrink-0" style="padding: 80px 15px 0">
        <?php
        $this->contentAdmin();
        ?>
    </main>

    <footer class="footer mt-auto">
        <div class="container-fluid rodape">
            <div class="col-12 text-center p-3">
                <?= APP_NAME .  ' &copy;'  . date('Y') ?>
            </div>
        </div>
    </footer>


    <script src="assets_admin/js/jquery.min.js"></script>
    <script src="assets_admin/js/bootstrap.bundle.min.js"></script>
    <script src="assets_admin/js/app.js"></script>

</body>

</html>