<!DOCTYPE html>
<html lang="pt-br" class="h-100">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sticky-footer-navbar/">
	<link rel="stylesheet" href="assets/css/bootstrap.min.css">
	<link rel="stylesheet" href="assets/css/all.min.css">
	<link rel="stylesheet" href="assets/css/app.css">
	<title><?= APP_NAME ?></title>
</head>

<body class="d-flex flex-column h-100">
	<header>
		<!-- Fixed navbar -->
		<nav class="navbar navbar-expand-md fixed-top navbar-dark menu">
			<div class="container-fluid">
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<a class="navbar-brand logo" href="/"><?= 'Gracy' ?></a>
				<div class="navbar-brand text-white">
					<a class="nav-link text-white" href="<?= BASE_URL ?>carrinho">
						<i class="fas fa-shopping-cart text-white"></i>
						<span id="carrinho" class="badge bg-light text-dark"><?= $this->view->quantidadeCarrinho ?></span>
					</a>
				</div>
				<div class="collapse navbar-collapse" id="navbarTogglerDemo03">
					<ul class="navbar-nav me-auto mb-2 mb-lg-0">
						<li class="nav-item">
							<a class="nav-link" aria-current="" href="<?= BASE_URL ?>"><i class="fas fa-home"></i> Home</a>
						</li>

						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
								<i class="far fa-list-alt"></i>
								Categorias
							</a>

							<ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
								<?php foreach ($this->view->categorias as $categoria) { ?>
									<a href="<?= BASE_URL ?>produtos?categoria=<?= $categoria->nome_categoria ?>" class="dropdown-item">
										<?= $categoria->nome_categoria ?>
									</a>
								<?php } ?>
								<li>
									<hr class="dropdown-divider">
								</li>
								<li><a class="dropdown-item" href="<?= BASE_URL ?>todos">Ver Todos</a></li>
							</ul>

						</li>

						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
								<i class="fas fa-comments"></i>
								Contatos
							</a>
							<ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
								<a href="https://api.whatsapp.com/send?phone=5585984064679" class="dropdown-item">
									<i class="fab fa-whatsapp"></i>
									WhatsApp
								</a>
								<a href="https://www.instagram.com/gracymodaeestilo/" class="dropdown-item">
									<i class="fab fa-instagram"></i>
									Intagram
								</a>
							</ul>
						</li>
						<?php if ($this->view->clienteLogado) { ?>
							<li class="nav-item">
								<a class="nav-link" href="<?= BASE_URL ?>minha_conta"><i class="fas fa-user"></i> Minha Conta</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="<?= BASE_URL ?>sair"><i class="fas fa-sign-out-alt"></i> Sair</a>
							</li>
						<?php } else { ?>
							<li class="nav-item">
								<a class="nav-link" aria-current="" href="<?= BASE_URL ?>login"><i class="fas fa-sign-in-alt"></i> Login</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="<?= BASE_URL ?>criar_conta"><i class="far fa-address-card"></i> Criar Conta</a>
							</li>
						<?php } ?>
					</ul>
					<form class="d-flex">
						<input class="form-control me-2" type="search" placeholder="Procurar por Produtos" aria-label="Search">
						<button class="btn btn-outline-light" type="submit">Search</button>
					</form>
				</div>
			</div>
		</nav>

	</header>
	<!-- Begin page content -->
	<main class="flex-shrink-0" style="padding: 80px 15px 0">
		<?php
		$this->content();
		?>
	</main>

	<footer class="footer mt-auto">
		<div class="container-fluid rodape">
			<div class="col-12 text-center p-3">
				<?= APP_NAME .  ' &copy;'  . date('Y') ?>
			</div>
		</div>
	</footer>

	<!-- Modal -->
	<div class="modal fade" id="modalEstoqueInvalido" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered modal-sm" role="document">
			<div class="modal-content">
				<div class="modal-header text-warning">
					<h3 class="modal-title">Ops...</h3>
				</div>
				<div class="modal-body">
					<p class="text-warning" id="modalText">
					<p>
				</div>
				<div class="modal-footer">
					<button id="closeModalEstoqueInvalido" class="btn btn-warning" type="button" data-dismiss="modal">Cotinuar comprando</button>
				</div>
			</div>
		</div>
	</div>

	<script src="assets/js/jquery.min.js"></script>
	<script src="assets/js/bootstrap.bundle.min.js"></script>
	<script src="assets/js/app.js"></script>

</body>

</html>